# Extacted from codex-universal/README.md
export CODEX_ENV_PYTHON_VERSION=3.12
export CODEX_ENV_NODE_VERSION=20
export CODEX_ENV_RUST_VERSION=1.87.0
export CODEX_ENV_GO_VERSION=1.23.8
export CODEX_ENV_SWIFT_VERSION=6.1
